name: Deploy to Salesforce Production
on:
  push:
    branches:
      - "sit"
jobs:
  Validate_Build_Test_Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "14"
          
      - name: Install Dependencies
        run: npm install

      - name: SFDX Auth
        env:
          SFDX_JWT_KEY: ${{ secrets.SFDX_JWT_KEY_SIT }}
          SFDX_CLIENT_ID: ${{ secrets.SFDX_CLIENT_ID_SIT }}
          SFDX_USERNAME: ${{ secrets.USERNAME_SIT }}
        run: |
          echo "${SFDX_JWT_KEY}" > server.key
          npx sfdx force:auth:jwt:grant --clientid "${SFDX_CLIENT_ID}" --jwtkeyfile server.key --username "${SFDX_USERNAME}" --instanceurl https://kubercicdsit-dev-ed.develop.my.salesforce.com --setalias sit --set-default-sit
          npx sfdx force:org:display --json -u "${SFDX_USERNAME}"  > sfdx-auth.json
          rm server.key

      - name: Build, Test & Deploy
        uses: gfarb/sfdx-deploy@v1
        env:
          TARGET_USERNAME: ${{ secrets.USERNAME_SIT }}
          SOURCE_PATH: force-app
          DESTRUCTIVE_CHANGES: ""
          TEST_LEVEL: RunLocalTests
          WAIT: 200
