name: Deploy to Salesforce Production
on:
  push:
    branches:
      - "sit"
jobs:
  Validate_Build_Test_Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "14"
          
      - name: Cache node modules
        uses: actions/cache@v3
        id: npm_cache_id
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.npm_cache_id.outputs.cache-hit != 'true'
        run: npm ci

      - name: SFDX Auth
        env:
          SFDX_JWT_KEY: ${{ secrets.SFDX_JWT_KEY_SIT }}
          SFDX_CLIENT_ID: ${{ secrets.SFDX_CLIENT_ID_SIT }}
          SFDX_USERNAME: ${{ secrets.USERNAME_SIT }}
        run: |
          echo "${SFDX_JWT_KEY}" > server.key
          npx sf org login jwt --client-id "${SFDX_CLIENT_ID}" --jwt-key-file server.key --username "${SFDX_USERNAME}" --instance-url https://kubercicdsit-dev-ed.develop.my.salesforce.com --alias sit --set-default
          npx sf org display --target-org sit
          rm server.key

      - name: Build, Test & Deploy
        uses: gfarb/sfdx-deploy@v1
        env:
          TARGET_USERNAME: ${{ secrets.USERNAME_SIT }}
          SOURCE_PATH: force-app
          DESTRUCTIVE_CHANGES: ""
          TEST_LEVEL: RunLocalTests
          WAIT: 200
